name: GitHub Actions Demo 2
on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
   - cron: "15 6 * * sun"
   
jobs:
  my_build:
    name: Build 
    runs-on: ubuntu-latest
    
    steps:
      - name: Provide feedback
        run: echo This is a message
    
  
